# Generated by Django 2.2.13 on 2020-06-07 00:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('firstname', models.CharField(max_length=50, null=True)),
                ('lastname', models.CharField(max_length=50, null=True)),
                ('contactdetails', models.IntegerField(null=True)),
                ('emailid', models.EmailField(max_length=254, null=True, unique=True)),
                ('addressdetails', models.CharField(max_length=500, null=True)),
                ('workexperience', models.CharField(max_length=20, null=True)),
                ('visastatus', models.CharField(max_length=20, null=True)),
                ('workpermit', models.CharField(max_length=100, null=True)),
                ('readytorelocate', models.CharField(max_length=20, null=True)),
                ('technology', models.TextField(max_length=200, null=True)),
            ],
        ),
    ]
